import type { Metadata } from 'next'
import './globals.css'
import dashboard from "@/styles/dashboardLayout.module.scss"

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={`${dashboard["main-body"]}`}>
        {children}
      </body>
    </html>
  )
}
